### ISSUE TITLE
Some questions when run gem

### ISSUE THREAD

**Issue by Doublezore** [G-U-N/PyCIL#10]
File "/home/doublezore/Code/Continual learning/PyCIL/models/gem.py", line 184, in _update_representation
    G[stpt:endpt, k].data.copy_(params.grad.data.view(-1))
AttributeError: 'NoneType' object has no attribute 'data'

After investigation, I found that in the last fc layer of the model, there is no forward propagation. I would like to ask you how to solve this problem?

**Comment by LightingMc** [comment]
@Doublezore @zhoudw-zdw whats the solution? I am having the same error.

**Comment by hxwu0717** [comment]
> [@Doublezore](https://github.com/Doublezore) [@zhoudw-zdw](https://github.com/zhoudw-zdw) whats the solution? I am having the same error.

have u solved this question?
