### ISSUE TITLE
 Genral idea for the code framework

### ISSUE THREAD

**Issue by Z-ZHIZHONG** [G-U-N/PyCIL#14]
Hello, I have some questions for you.Is your code modified from the original DER? Could you give me a general idea of your thinking.Thank you very much. I look forward to your recovery.

**Comment by G-U-N** [comment]
Our code is not modified from the `original DER`. What do you mean by saying the `general idea`? Is it about the code framework?

- `convs`: the CNNs
-  `exps`: config files
-  `utils/inc_net`: the networks specially designed for class-incremental learning 
-  `utils/data_manager`: `data_manager` for collecting data and adding pre_processing at each session
-  `utils/data`: basic configs for different datasets
-  `models`: incremental algorithms.  Every algorithm inherits the class `BaseLearner`.  For arbitrary methods, the function `Increment_train` must be implemented. You can refer to implemented algos for more details.

Hope this can help you.

**Comment by Z-ZHIZHONG** [comment]
Thank you very much for your patience and detailed answers
