### ISSUE TITLE
What is the purpose of the reduce Exemplar function

### ISSUE THREAD

**Issue by Z-ZHIZHONG** [G-U-N/PyCIL#15]
I'd like to know the role of the Reduce examplar functions, construct examplar functions, and construct Exemplar unified functions in your base.py file. Is there a reference for how they work?

**Comment by G-U-N** [comment]
You can refer to the paper iCaRL to understand why we define them in this way. It is a typical benchmark.

**Comment by Z-ZHIZHONG** [comment]
thanks
