### ISSUE TITLE
ImageNet100各方法精度

### ISSUE THREAD

**Issue by misaka-mio** [G-U-N/PyCIL#17]
您好，我没找到利用ResNet18作为backbone的ImageNet100的top1精度，看到您这里有，所以想咨询下方便给出以ResNet18而不是32 为backbone的WA，BiC，iCaRL，DER，DER w/o p的每个session的top1精度和最终avg精度吗？谢谢了

**Comment by G-U-N** [comment]
感谢您的关注！您可以查看我们的中文综述中的结果 [CIL_survey](http://www.lamda.nju.edu.cn/zhoudw/file/cil_survey.pdf) 作为参考，或者访问[google drive](https://drive.google.com/file/d/1UKaX2_Q14V-zCEGDOl8d6yVhcrlEL_N1/view?usp=sharing)。

希望这能帮助到您。

**Comment by misaka-mio** [comment]
感谢您的回答，我拜读了您的FOSTER在ECCV2022，有个疑问您的论文并没有提及cutout但是您的代码使用了cutout，我测试了下不含cutout的精度似乎不是很尽如人意，我用含cutout的您的代码复现了您的精度，所以我想咨询下cutout是真的是公平，还是因为没有改变targets所以默许使用
