### ISSUE TITLE
Packages import problem

### ISSUE THREAD

**Issue by woodszp** [G-U-N/PyCIL#18]
Hi~
I have a problem, about import ot package.
Could you help me slove it? or Did you mind tell me where can i download?
Thank you~

**Comment by woodszp** [comment]
> Hi~ I have a problem, about import ot package. Could you help me slove it? or Did you mind tell me where can i download? Thank you~

yet I have been slove it.

pip install pot
pip install geomloss

It will be work.

**Comment by G-U-N** [comment]
Thanks for your interest. 

Any problems, feel free to reopen this issue or contact us with email (zhoudw@lamda.nju.edu.cn, wangfuyun@smail.nju.edu.cn) directly.
