### ISSUE TITLE
关于FOSTER的数据增强

### ISSUE THREAD

**Issue by qsunyuan** [G-U-N/PyCIL#19]
FOSTER很令我感兴趣的工作。

我尝试了cifar100的benchmark的设置。

我发现pycil中的实现并没有数据增强，如：https://github.com/G-U-N/ECCV22-FOSTER/blob/340fbd1a16ca6a787e522b9dc349a5e742f00c30/utils/data.py#L73

因此，pycil的实现结果要差一点。请问还有其他的一些细节上的不同吗？

**Comment by G-U-N** [comment]
您好，非常感谢您的关注。 

在具体的实现细节上并没有其他的不同，但是需要指出的是即使去掉数据增强，pycil仍然能够在大部分的protocols下达到sota的性能。

另外需要指出的是，pycil的版本中的FOSTER并没有进行仔细的调优，这主要包含以下几个方面的影响：
1. 需要重新选择最优的超参数β，请尝试重新选择超参数beta1，beta2。
2. 需要重新确定优化器设置，可以尝试将余弦退火算法替换为一般的多阶段衰减算法并选择合适的milestone等。

希望我的回答能帮到您。

**Comment by qsunyuan** [comment]
我的一些尝试结果如下：

CIFAR100 B0 10 steps

1. 原始的SOTA：

CNN: [93.8, 85.0, 80.77, 75.47, 72.04, 69.85, 68.33, 64.42, 62.92, 61.93]
NME: [93.7, 84.6, 80.27, 74.68, 70.06, 66.58, 63.89, 58.79, 55.58, 52.63]

2. 原始的仅仅删除数据增强，即删除Policy和Cutout，其余学习率，schedule等等保持一致。

```
    train_trsf = [
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ColorJitter(brightness=63/255),
        # CIFAR10Policy(),
        transforms.ToTensor(),
        # Cutout(n_holes=1, length=16),
    ]
```
CNN: [89.8, 80.25, 75.8, 66.92, 62.2, 58.65, 56.69, 53.04, 51.92, 51.2] 
NME: [89.6, 81.2,   76.17, 70.2, 65.46, 59.92,  56.97, 51.96,  50.6,  48.11]

3. 修改为milestone的结果，有一定提升。

no-trick + milestone schedule. (0.1的学习率衰减，分别在80，120 epoch) (包括boosting和compression)

CNN: [90.5, 79.55, 75.57, 68.18, 63.72, 60.1, 58.43, 54.94, 53.83, 53.33]
NME: [90.2, 80.4, 77.03, 70.22, 65.74, 61.97, 59.07, 53.35, 51.67, 49.58]

4. 修改beta，效果变得很差。

可能并不是很轻易的能够调到SOTA，但是milestone的效果确实比较明显。

**Comment by G-U-N** [comment]
您好，感谢您的尝试。

另外，针对
> 修改beta，效果变得很差。

可能是因为并没有选择合适的超参数，可以尝试使用 $\beta_1=\beta_2=0.97$，应该能观察到明显的性能提升。
