### ISSUE TITLE
memory_size，memory_per_class

### ISSUE THREAD

**Issue by LifeIsBright-heihei** [G-U-N/PyCIL#2]
Hello, thank you very much for the code you provided. Can you tell me what the parameter memory_size and memory_per_class represents？

**Comment by LifeIsBright-heihei** [comment]
If the number of pictures in the second increment is much smaller than that in the first increment, how should I set these two parameters

**Comment by G-U-N** [comment]
When fixed memory is set to false, memory size is used, which means that we keep memory size images for all the old classes, which means that for each of the k old categories, we keep memory size/k(floor) images. 

On the contrary, when fixed memory is set to true, memory_per_class will be used, which means that we will keep memory_per_class images for each category. In other words, its memory size increases with the number of categories.

**Comment by G-U-N** [comment]
In most cases, to be fair, when training cifar100 and imagenet100, we set memory size to 2000, and when training imagenet1000, we set memory size to 20000.

**Comment by LifeIsBright-heihei** [comment]
> When fixed memory is set to false, memory size is used, which means that we keep memory size images for all the old classes, which means that for each of the k old categories, we keep memory size/k(floor) images.
> 
> On the contrary, when fixed memory is set to true, memory_per_class will be used, which means that we will keep memory_per_class images for each category. In other words, its memory size increases with the number of categories.

I probably understand. Thank you for your explanation

**Comment by G-U-N** [comment]
Thanks for your interests. 😊
