### ISSUE TITLE
the memory of rmm

### ISSUE THREAD

**Issue by zhl98** [G-U-N/PyCIL#21]
Hello! 
First of all, thank you very much for your work.When I read the rmm code, I found that memory is not 2000. Instead, only 2000 pieces of data were used for the new task. Is rmm originally like this?
I add the following code to rmm.py to see the number of memories.

![image](https://user-images.githubusercontent.com/51871747/203264337-f638a702-b540-4406-b2ba-cbfb8e0b6710.png)
![image](https://user-images.githubusercontent.com/51871747/203264592-d2e6fe1f-aa1c-4f18-8b12-a58285bc9cc3.png)

**Comment by G-U-N** [comment]
Hi, thanks for your interest!

This is the exactly the motivation behind RMM: 

> We assume we have a unified memory budget, and we can use it for both old and new data. In previous work, the existing papers don’t have a specific definition of “what is the memory budget”. In our understanding, we need to store both old and new data in the memory, because we also need to train the model on the new data for many epochs. If you assume you don’t need a memory budget for the new data, you cannot observe each new sample more than once.

To put it simply, we discard some new training samples (i.e. randomly select a small amount of new sample training), so as to allow us to restore more old samples. 

The reinforcement learning algorithm aims to find the optimal ratios listed as `m_rate_list` and `c_rate_list`. 

Hope this clarifies your queries.

**Comment by zhl98** [comment]
Thank you. Thank you very much for your answer.
