### ISSUE TITLE
Missing configs for Imagenet-Subset

### ISSUE THREAD

**Issue by grypesc** [G-U-N/PyCIL#25]
Hey, thank you for this benchmark. I'm trying to reproduce your results for Imagenet-Subset dataset with 50+5x10 split. I am unable to achieve your accuracy (85%) after first task, I get 80%. Can you share experiment configs?

**Comment by caoshuai888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhoudw-zdw** [comment]
Hi, thanks for your interests in our work.

The figure of ImageNet100 comes from our work FOSTER. If you are going to reproduce the results in these figures, please refer to the source code of [FOSTER](https://github.com/G-U-N/ECCV22-FOSTER) and its [data augmentations](https://github.com/G-U-N/ECCV22-FOSTER/blob/master/utils/autoaugment.py).
