### ISSUE TITLE
fetril cifar10 got error

### ISSUE THREAD

**Issue by muyuuuu** [G-U-N/PyCIL#27]
config:

```
{
    "prefix": "train",
    "dataset": "cifar10",
    "memory_size": 0,
    "shuffle": true,
    "init_cls": 2,
    "increment": 2,
    "model_name": "fetril",
    "convnet_type": "resnet18",
    "device": ["0"],
    "seed": [1993],
    "init_epochs": 200,
    "init_lr" : 0.1,
    "init_weight_decay" : 0,
    "epochs" : 50,
    "lr" : 0.1,
    "batch_size" : 128,
    "weight_decay" : 0,
    "num_workers" : 8,
    "T" : 2
}
```

error message:

```
Traceback (most recent call last):
  File "fetril.py", line 31, in <module>
    main()
  File "fetril.py", line 12, in main
    train(args)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/trainer.py", line 18, in train
    _train(args)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/trainer.py", line 67, in _train
    model.incremental_train(data_manager)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/fetril.py", line 88, in incremental_train
    self._train(self.train_loader, self.test_loader)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/fetril.py", line 105, in _train
    self._train_function(train_loader, test_loader, optimizer, scheduler)
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/fetril.py", line 178, in _train_function
    for i, (_, inputs, targets) in enumerate(train_loader):
  File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/20031211496/Documents/PYCIL/PyCIL-master/utils/data_manager.py", line 207, in __getitem__
    image = self.trsf(Image.fromarray(self.images[idx]))
  File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
    img = t(img)
  File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 98, in __call__
    return F.to_tensor(pic)
  File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 114, in to_tensor
    raise TypeError('pic should be PIL Image or ndarray. Got {}'.format(type(pic)))
TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>
```

**Comment by G-U-N** [comment]
It's fixed.

**Comment by valeriya-khan** [comment]
> config:
> 
> ```
> {
>     "prefix": "train",
>     "dataset": "cifar10",
>     "memory_size": 0,
>     "shuffle": true,
>     "init_cls": 2,
>     "increment": 2,
>     "model_name": "fetril",
>     "convnet_type": "resnet18",
>     "device": ["0"],
>     "seed": [1993],
>     "init_epochs": 200,
>     "init_lr" : 0.1,
>     "init_weight_decay" : 0,
>     "epochs" : 50,
>     "lr" : 0.1,
>     "batch_size" : 128,
>     "weight_decay" : 0,
>     "num_workers" : 8,
>     "T" : 2
> }
> ```
> 
> error message:
> 
> ```
> Traceback (most recent call last):
>   File "fetril.py", line 31, in <module>
>     main()
>   File "fetril.py", line 12, in main
>     train(args)
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/trainer.py", line 18, in train
>     _train(args)
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/trainer.py", line 67, in _train
>     model.incremental_train(data_manager)
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/fetril.py", line 88, in incremental_train
>     self._train(self.train_loader, self.test_loader)
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/fetril.py", line 105, in _train
>     self._train_function(train_loader, test_loader, optimizer, scheduler)
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/fetril.py", line 178, in _train_function
>     for i, (_, inputs, targets) in enumerate(train_loader):
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
>     return self._process_data(data)
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
>     data.reraise()
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
>     raise exception
> TypeError: Caught TypeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/utils/data_manager.py", line 207, in __getitem__
>     image = self.trsf(Image.fromarray(self.images[idx]))
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
>     img = t(img)
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 98, in __call__
>     return F.to_tensor(pic)
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 114, in to_tensor
>     raise TypeError('pic should be PIL Image or ndarray. Got {}'.format(type(pic)))
> TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>
> ```

I have this error, and it is in the master. Can you tell me how to fix this?

**Comment by Hephaestusxg** [comment]
> It's fixed.

mnist meet this error i have some question about create ownerdatasets

**Comment by Hephaestusxg** [comment]
> config:
> 
> ```
> {
>     "prefix": "train",
>     "dataset": "cifar10",
>     "memory_size": 0,
>     "shuffle": true,
>     "init_cls": 2,
>     "increment": 2,
>     "model_name": "fetril",
>     "convnet_type": "resnet18",
>     "device": ["0"],
>     "seed": [1993],
>     "init_epochs": 200,
>     "init_lr" : 0.1,
>     "init_weight_decay" : 0,
>     "epochs" : 50,
>     "lr" : 0.1,
>     "batch_size" : 128,
>     "weight_decay" : 0,
>     "num_workers" : 8,
>     "T" : 2
> }
> ```
> 
> error message:
> 
> ```
> Traceback (most recent call last):
>   File "fetril.py", line 31, in <module>
>     main()
>   File "fetril.py", line 12, in main
>     train(args)
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/trainer.py", line 18, in train
>     _train(args)
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/trainer.py", line 67, in _train
>     model.incremental_train(data_manager)
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/fetril.py", line 88, in incremental_train
>     self._train(self.train_loader, self.test_loader)
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/fetril.py", line 105, in _train
>     self._train_function(train_loader, test_loader, optimizer, scheduler)
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/models/fetril.py", line 178, in _train_function
>     for i, (_, inputs, targets) in enumerate(train_loader):
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
>     return self._process_data(data)
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
>     data.reraise()
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
>     raise exception
> TypeError: Caught TypeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
>     data = [self.dataset[idx] for idx in possibly_batched_index]
>   File "/home/20031211496/Documents/PYCIL/PyCIL-master/utils/data_manager.py", line 207, in __getitem__
>     image = self.trsf(Image.fromarray(self.images[idx]))
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 61, in __call__
>     img = t(img)
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 98, in __call__
>     return F.to_tensor(pic)
>   File "/home/20031211496/.conda/envs/drive/lib/python3.8/site-packages/torchvision/transforms/functional.py", line 114, in to_tensor
>     raise TypeError('pic should be PIL Image or ndarray. Got {}'.format(type(pic)))
> TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>
> ```

“Can we increment by adding only one class at a time?”
