### ISSUE TITLE
how to resume training 

### ISSUE THREAD

**Issue by ahsan856jalal** [G-U-N/PyCIL#29]
How can we resume training if PC shuts down or hangs due to some issue.

**Comment by G-U-N** [comment]
Directly resuming training is not supported right now, though you can manually save the state of your backbone by adding `self.save_checkpoint(filename)` in `def after_task():`.

**Comment by ahsan856jalal** [comment]
@G-U-N  can you please guide me how to load these pkl file and predict using these saved weights. I have saved the model for DER using cifar 100 for intiial phase trained with 50 classes but unable to load and predict using it
[model_der_phase_0.zip](https://github.com/G-U-N/PyCIL/files/10720512/model_der_phase_0.zip)

**Comment by zhoudw-zdw** [comment]
Maybe you can check this page.

https://pytorch.org/tutorials/beginner/saving_loading_models.html
