### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by aooating** [G-U-N/PyCIL#3]
when I run the experiment using : 
python main.py --config=./exps/finetune.json
it occurs : 
FileNotFoundError: [Errno 2] No such file or directory: '/data7/PyCIL-master/logs/reproduce_1993_finetune_resnet32_cifar100_10_10.log'
so I want to ask if the author forgets to upload the repository "/logs" or I need to train by myself.

**Comment by G-U-N** [comment]
Sorry, but you can only train to get the log now, and we may upload a more comprehensive experiment log in the near future.
