### ISSUE TITLE
Not an Issue 

### ISSUE THREAD

**Issue by ElifCerenGokYildirim** [G-U-N/PyCIL#30]
Hi, 

The reason I open this issue is not that it is an issue it is more of a request. PYCIL is a good resource to use. I am actually using it, especially for regularization-based approaches. I was wondering if you have plans to add more reg-based methods like Synaptic Intelligence: https://arxiv.org/pdf/1703.04200.pdf That would be awesome!

**Comment by zhoudw-zdw** [comment]
Hi,

Thanks for your interest in our work. Regularization-based methods are hot topics in the class-incremental learning field, and we hope to include more of them in the repo. 

However, the current repo is maintained by several researchers with busy workloads. Currently, we aim to keep track of the up-to-date state-of-the-art in top conferences for the researchers to reproduce and design their original algorithms. Hence, the reproduction of SI may have a lower priority than them.

We hope you understand, and we will be happy to merge these important methods into our repo if someone has it adequately reproduced.

Best,
Da-Wei
