### ISSUE TITLE
A problem regarding the replication of PASS on other datasets.

### ISSUE THREAD

**Issue by ShiWuxuan** [G-U-N/PyCIL#33]
Thank you for the excellent work. 
Regarding the self-supervision of PASS, the image size was fixed to 32 when the augmentation was performed (around line 108 of pa2s.py). The image size should be set according to the dataset, otherwise it will report an error on datasets other than CIFAR.

**Comment by caoshuai888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by G-U-N** [comment]
Thank you very much for your advice and interest. However, I am currently very busy. If you have implemented a better way to modify additional data augmentation, I would welcome a pull request. Alternatively, in the future, I will improve this implementation.
