### ISSUE TITLE
How to display the confusion matrix in the pycil framework, taking the wa method as an example

### ISSUE THREAD

**Issue by Fenghao1995** [G-U-N/PyCIL#34]

**Comment by caoshuai888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zhoudw-zdw** [comment]
We did not report confusion matrix in the PyCIL paper.

However, you can refer to [sklearn.metrics.confusion_matrix](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) for it.
