### ISSUE TITLE
Why does der use softmax for training and NME for testing? The original classifiers are all softmax?

### ISSUE THREAD

**Issue by Z-ZHIZHONG** [G-U-N/PyCIL#37]
Why does der use softmax for training and NME for testing? The original classifiers are all softmax?

**Comment by zhoudw-zdw** [comment]
I think we provide both CNN accuracy and NME accuracy for testing. Just choose what you want.

You can also refer to [iCaRL: Incremental Classifier and Representation Learning](https://arxiv.org/abs/1611.07725), which is an abc book in CIL and introduces the reason of NME.
