### ISSUE TITLE
Question of DER: freeze the old module is left out in the file der.py

### ISSUE THREAD

**Issue by fanyan0411** [G-U-N/PyCIL#40]
Why "freezing old  network" of after_task is left out in file der.py, while other methods, such as podnet and WA execute this step as follows:  
self._old_network = self._network.copy().freeze()?

**Comment by G-U-N** [comment]
Hi, thanks for your interest. WA and PodNet are distillation-based methods, meaning they have to save the model in the last incremental session, while DER does not.

**Comment by fanyan0411** [comment]
Thanks for your timely responce!

In original paper, DER noticed that "we freeze the previously learned representation" for several times. If the previous convs in self.convnets are not freezed, which is also not executed in the code, does it means that those previous "resnet" modules will be affected by the back propagation? How to understand "freeze the previously learned representation"?

**Comment by G-U-N** [comment]
I understand your confusion now. Refer to [Line51](https://github.com/G-U-N/PyCIL/blob/master/models/der.py#L51) and [Line84](https://github.com/G-U-N/PyCIL/blob/master/models/der.py#L84).

**Comment by fanyan0411** [comment]
That the key point I am wondering about. Thanks a lot! 

I hope your work keeps getting better！
