### ISSUE TITLE
Whether the code can be applied to object detection such as yolo?

### ISSUE THREAD

**Issue by ishulei** [G-U-N/PyCIL#42]
Hello, is ur code only applicable to classification networks? Can  it be used in object detection networks? I want to implement EWC on YOLO, and I wonder if u have relevant suggestions.  Thank u for ur work and acvice.

**Comment by haoduoylgzz** [comment]
I'm also interested in this particular question. Any guidance or suggestions would be greatly appreciated.

**Comment by zhoudw-zdw** [comment]
Hello,

Since the team for this project does not have the background for broader cv tasks, we only focus on the general classification tasks. But I think there are many works addressing incremental object detection, where you can refer to for more details.
