### ISSUE TITLE
problems about dataset

### ISSUE THREAD

**Issue by zhangjic22** [G-U-N/PyCIL#43]
Thanks for your excellent work! 
Could you please offer some instructions about preparing ImageNet-100/ImageNet-1000? Are ImageNet-Subset and ImageNet-100 the same dataset?

**Comment by zhoudw-zdw** [comment]
That should be the first 100 classes of Imagenet1000 after random shuffle with 1993. The datasets you mentioned are the same.

You can check this repo for the list. https://github.com/G-U-N/ECCV22-FOSTER/tree/master/imagenet-sub

**Comment by zhangjic22** [comment]
Thank you very much for your timely response!
