### ISSUE TITLE
DER。mask

### ISSUE THREAD

**Issue by kaikai123456789** [G-U-N/PyCIL#47]
Hello, I would like to ask where the mask is located in the DER code?
thanks

**Comment by zhoudw-zdw** [comment]
It seems the original repo of DER also does not cotain the code for masking and pruning. The reproduction in this repo only contains the network expansion process, which is proven to work robustly in most cases.

**Comment by kaikai123456789** [comment]
We noticed that the original DER paper mentions the “Our pruning method is based on differentiable channel-level masks, which is adapted from HAT” section, which discusses masking. Therefore, there is some confusion. Thank you very much for your answer.
