### ISSUE TITLE
where's the trained model? where can I see the classification result?

### ISSUE THREAD

**Issue by Jung-Echo** [G-U-N/PyCIL#54]
I am eager to apply incremental learning not only in academic papers, for example, just evaluating model accuracy results; but also in practical scenarios, such as enabling continuous evolution of the model. However, after studying some incremental learning code, I have not yet found any that involve saving the trained model for further retraining, or simply saving the incrementally trained model for future classification tasks. I wonder what your thoughts are on this? If there are any difficulties or complexities in such an implementation, could you please provide me with some guidance? I would greatly appreciate your help in resolving my doubts!

**Comment by zhoudw-zdw** [comment]
Saving and loading model is very simple in Pytorch. You can refer to this issue. 

https://github.com/G-U-N/PyCIL/issues/32#issuecomment-1437286772

**Comment by Jung-Echo** [comment]
> Saving and loading model is very simple in Pytorch. You can refer to this issue.
> 
> [#32 (comment)](https://github.com/G-U-N/PyCIL/issues/32#issuecomment-1437286772)

It's my ignorance hhh, thank you for your answer. I probably understand that some functions still have to be developed and solved by ourselves.

**Comment by Hephaestusxg** [comment]
> > Saving and loading model is very simple in Pytorch. You can refer to this issue.
> > [#32 (comment)](https://github.com/G-U-N/PyCIL/issues/32#issuecomment-1437286772)
> 
> It's my ignorance hhh, thank you for your answer. I probably understand that some functions still have to be developed and solved by ourselves.

sry to bother u，i have some question about saving model.
