### ISSUE TITLE
About distributed training

### ISSUE THREAD

**Issue by zhengyuan-xie** [G-U-N/PyCIL#57]
Thank you for your great work! I see podnet.json has key-value pair: "device": ["0", "1", "2", "3"], but when I run this config, only cuda:0 was used and I didn't find the code about DP or DDP. Hope you can help me, Thanks!

**Comment by zhoudw-zdw** [comment]
You can make a simple modification like this.

 https://github.com/G-U-N/PyCIL/blob/0b99ae5c4ea34df1c913c15e1d366a9e718e7569/models/foster.py#L86

**Comment by zhengyuan-xie** [comment]
> You can make a simple modification like this.
> 
> https://github.com/G-U-N/PyCIL/blob/0b99ae5c4ea34df1c913c15e1d366a9e718e7569/models/foster.py#L86

Thanks for your reply!
