### ISSUE TITLE
[Question] What about edge cases?

### ISSUE THREAD

**Issue by kirk86** [G-U-N/PyCIL#58]
PyCIL is a toolbox/library that provides out the box implemented methods for CIL but how/can it be used to fit the needs of users in different scenarios? e.g. some might want to use the methods of PyCIL in DIL instead of CIL or develop their own methods, is there any explanation on how to achieve that, if possible?

**Comment by zhoudw-zdw** [comment]
Hi, thanks for your interest in our work.

Could you be more specific about your question? Do you mean extending PyCIL to domain-incremental learning?

**Comment by G-U-N** [comment]
You can refer to [S-Prompt](https://github.com/iamwangyabin/S-Prompts), a domain-incremental learning method. The code base is heavily built upon PyCIL.
