### ISSUE TITLE
The implementation of DER

### ISSUE THREAD

**Issue by zihuanqiu** [G-U-N/PyCIL#6]
Hi,
I note the bias-correct method used in your implementation of DER is WA but not the balanced fine-tune, which is not identical with the original paper.  I wonder why do you decide to change it to WA? :)

**Comment by G-U-N** [comment]
Good question! The most direct reason is that WA is an effective strategy to achieve bias correction with negligible additional training costs.  The official code of DER also implements WA as an optional procedure.  We will implement more optional calibration methods such as finetune, feature aug, and IL2M et al. in the future.

**Comment by zihuanqiu** [comment]
Thanks!

**Comment by Z-ZHIZHONG** [comment]
hello, I'd like to know the role of the _Reduce_examplar functions, _construct_examplar functions, and _construct_Exemplar_unified functions in your base.py file. Is there a reference for how they work?
