### ISSUE TITLE
How to prepare image100 dataset

### ISSUE THREAD

**Issue by JACK-Chen-2019** [G-U-N/PyCIL#61]
def download_data(self):
        assert 0, "You should specify the folder of your dataset"
        train_dir = "[DATA-PATH]/train/"
        test_dir = "[DATA-PATH]/val/"

        train_dset = datasets.ImageFolder(train_dir)
        test_dset = datasets.ImageFolder(test_dir)

        self.train_data, self.train_targets = split_images_labels(train_dset.imgs)
        self.test_data, self.test_targets = split_images_labels(test_dset.imgs)

In utils/data.py, iImageNet1000 and iImageNet100 have the same code. How can use the file list of ImageNet100 (in readme) to prepare imagenet100 dataset?

**Comment by zhoudw-zdw** [comment]
A simple solution is to write a code to copy the images from ImageNet1000 to a new folder. Afterward, you can construct the ImageNet100 dataset. I think ChatGPT is good at doing these tedious issues.
