### ISSUE TITLE
Podnet Configuration

### ISSUE THREAD

**Issue by nttung1110** [G-U-N/PyCIL#62]
Hi,

Thanks for your interesting work! Could I ask what the conv_net type for Podnet  is in terms of the experiment for Imagenet1k? It might be resnet 18 but there are multiple resnet18 version on your file so it would be great if you could also specify the corresponding conv_net for Imagenet1k dataset.

Thanks!

**Comment by zhoudw-zdw** [comment]
You can try this config.

https://github.com/zhoudw-zdw/CIL_Survey/blob/main/scripts/benchmark/img1000_b0_100_podnet.sh
