### ISSUE TITLE
Could you add our model to your responsity?

### ISSUE THREAD

**Issue by JiahuaDong** [G-U-N/PyCIL#66]
Hi, authors:
 Could you add our model to your responsity? Our paper "Heterogeneous Forgetting Compensation for Class-Incremental Learning" is published at ICCV 2023. We can share the source code with you.

best,
jiahua

**Comment by G-U-N** [comment]
Thank you for your willingness to contribute. Please initiate a new pull request, and I'll review it promptly. To maintain the clarity and simplicity of our codebase, kindly ensure your changes are concise and refrain from adding superfluous components. We appreciate your valuable input to our repository

**Comment by caoshuai888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
