### ISSUE TITLE
 Why is there no downsampling in the first convolution layer of resnet for imagenet dataset?

### ISSUE THREAD

**Issue by linlany** [G-U-N/PyCIL#67]
https://github.com/G-U-N/PyCIL/blob/07c9114d8b9be1534185ab1d9b36f1709867c7f0/convs/resnet.py#L174
This setting is usually applied to low-resolution datasets such as cifar100 to avoid too small feature maps. If the imagenet dataset also uses this setting, it will result in feature maps that are four times larger than the original resnet, which consumes a lot of memory and is not a common setting.

**Comment by Hong753** [comment]
I was also wondering about this. Wish there was an explanation for each case.
On top of that, usually the maxpool layer is removed for small resolution datasets such as C-10/100.

**Comment by caoshuai888** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by LightingMc** [comment]
@Hong753 @linlany @caoshuai888 I am also confused as for why their implementation is slightly different from deafault resnet implementation?

Default pytorch resnet has this config https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py:

        x = self.conv1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.fc(x)



while their config looks like this:

        # See note [TorchScript super()]
        x = self.conv1(x)  # [bs, 64, 32, 32]

        x_1 = self.layer1(x)  # [bs, 128, 32, 32]
        x_2 = self.layer2(x_1)  # [bs, 256, 16, 16]
        x_3 = self.layer3(x_2)  # [bs, 512, 8, 8]
        x_4 = self.layer4(x_3)  # [bs, 512, 4, 4]

        pooled = self.avgpool(x_4)  # [bs, 512, 1, 1]
        features = torch.flatten(pooled, 1)  # [bs, 512]

**Comment by zhoudw-zdw** [comment]
Please check this issue https://github.com/G-U-N/PyCIL/issues/80

Feel free to modify the code for your own implementation.
