### ISSUE TITLE
about memory size and train

### ISSUE THREAD

**Issue by Hephaestusxg** [G-U-N/PyCIL#76]
In the init cls phase, is the incremental learning method used? If I want the initial class to be 7, then in the 0-6 phase of training, is the incremental learning method used, and can I save the weights? Secondly, regarding the memory size, how much should I set for small datasets like cifar10?

**Comment by zhoudw-zdw** [comment]
Of course, you can save the model weights. You might want to read the Pytorch tutorial on how to save and load models.

The memory size should be adjusted for your own datasets, and we cannot give specific suggestions.
