### ISSUE TITLE
PyCil's Resnet different from Default implementation? Why?

### ISSUE THREAD

**Issue by LightingMc** [G-U-N/PyCIL#81]
I am also confused as for why their implementation is slightly different from deafault resnet implementation?

Default pytorch resnet has this config https://github.com/pytorch/vision/blob/main/torchvision/models/resnet.py:

    x = self.conv1(x)
    x = self.bn1(x)
    x = self.relu(x)
    x = self.maxpool(x)

    x = self.layer1(x)
    x = self.layer2(x)
    x = self.layer3(x)
    x = self.layer4(x)

    x = self.avgpool(x)
    x = torch.flatten(x, 1)
    x = self.fc(x)
while their config looks like this:

    # See note [TorchScript super()]
    x = self.conv1(x)  # [bs, 64, 32, 32]

    x_1 = self.layer1(x)  # [bs, 128, 32, 32]
    x_2 = self.layer2(x_1)  # [bs, 256, 16, 16]
    x_3 = self.layer3(x_2)  # [bs, 512, 8, 8]
    x_4 = self.layer4(x_3)  # [bs, 512, 4, 4]

    pooled = self.avgpool(x_4)  # [bs, 512, 1, 1]
    features = torch.flatten(pooled, 1)  # [bs, 512]

**Comment by G-U-N** [comment]
They are exactly the same. In our code, conv1 = nn.Sequential (...). Again, please use "you" and be polite for proposing issue.

**Comment by LightingMc** [comment]
Oh. I didn't see the self.conv1 using nn.Sequential. Thanks, appreciate it.
