### ISSUE TITLE
low accuracy on ewc

### ISSUE THREAD

**Issue by psychocosine** [G-U-N/PyCIL#82]
When I tried to run ```python main.py --config ./exps/ewc.json```. It seems that the accuracy of the tasks learned previously is very low. Why it happened？
![image](https://github.com/G-U-N/PyCIL/assets/62004255/026cd703-7316-45b6-8a91-371da9998fc3)

ewc.json
```
{
    "prefix": "reproduce",
    "dataset": "cifar100",
    "memory_size": 2000,
    "memory_per_class": 20,
    "fixed_memory": false,
    "shuffle": true,
    "init_cls": 10,
    "increment": 10,
    "model_name": "ewc",
    "convnet_type": "resnet32",
    "device": ["0","1","2","3"],
    "seed": [1993]
}
```

**Comment by zhoudw-zdw** [comment]
It means EWC is not a strong baseline.
