### ISSUE TITLE
About DER

### ISSUE THREAD

**Issue by Hephaestusxg** [G-U-N/PyCIL#84]
Hello, sorry to bother you. I’ve saved the weights, but it feels like the resnet20 model is too small, and when I print out the network, I find that the fc is always a 10-classifier. If I only train 7 classes initially, shouldn’t there only be a 7-classifier?   （model is resnet20
![der](https://github.com/G-U-N/PyCIL/assets/137689049/52895dfb-12d9-4cf1-ade8-3b3e9b100ca9)
）
![der1](https://github.com/G-U-N/PyCIL/assets/137689049/35378238-cbc7-4f20-9404-48623109fd77)
![der2](https://github.com/G-U-N/PyCIL/assets/137689049/d46a1a4f-4b54-4608-bc4a-089d3c1cc96e)

**Comment by zhoudw-zdw** [comment]
The way of classifier is defined by the number of classes you choose in the training stage.

**Comment by MoSheng37** [comment]
> 分类器的方式由您在训练阶段选择的类数定义。
你好，为什么权重保存下来这么小呢

**Comment by zhoudw-zdw** [comment]
Please refer to the original ResNet paper for details on why the model has so few parameters. Note that Issues are not designed to teach basic deep learning details.

**Comment by Hephaestusxg** [comment]
> Please refer to the original ResNet paper for details on why the model has so few parameters. Note that Issues are not designed to teach basic deep learning details.



> Please refer to the original ResNet paper for details on why the model has so few parameters. Note that Issues are not designed to teach basic deep learning details.

I saved the weights and loaded them according to the model in training, but the accuracy of the tests is very low. Why is this happening?

![2](https://github.com/G-U-N/PyCIL/assets/137689049/560cdf1f-6d98-4992-90c4-a5c9e71bec58)
![3](https://github.com/G-U-N/PyCIL/assets/137689049/8325c512-59eb-4c33-bc6b-912e0034cce4)
![1](https://github.com/G-U-N/PyCIL/assets/137689049/1c0e9f55-c459-4dee-93fd-829bc20dcd46)

**Comment by Hephaestusxg** [comment]
> Please refer to the original ResNet paper for details on why the model has so few parameters. Note that Issues are not designed to teach basic deep learning details.

sry  can u tell me  the reason？
