### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by MoSheng37** [G-U-N/PyCIL#86]
Can I incrementally train on top of the pre-trained ResNet weights for 7 classes? I haven't seen where in the code this is possible.

**Comment by zhoudw-zdw** [comment]
https://github.com/G-U-N/PyCIL/blob/a9b1ec8e3dbbe143cb72b008d7c8f946629d55b1/models/finetune.py#L39

You need to load model before incremental train. If you do not understand the code and do not want to modify it by yourself, maybe you can ask help from ChatGPT.
