### ISSUE TITLE
about class 

### ISSUE THREAD

**Issue by Hephaestusxg** [G-U-N/PyCIL#89]
Is it possible to increment by only one category at a time?

**Comment by zhoudw-zdw** [comment]
See https://github.com/G-U-N/PyCIL?tab=readme-ov-file#run-experiment

**Comment by Hephaestusxg** [comment]
> See https://github.com/G-U-N/PyCIL?tab=readme-ov-file#run-experiment

i try set 1class per stage . i
 see the reult is true. and papers have the same sets.
