### ISSUE TITLE
Weird Training Result with train_acc=0 & loss=0

### ISSUE THREAD

**Issue by Steven-cpp** [G-U-N/PyCIL#9]
Thanks for your excellent work!

But when I tried my own dataset on it, I found that the training result was really weired, just take EWC as an example:

```
================ EWC ================
Task 0, Epoch 200/200 => Loss 0.886, Train_accy 70.60, Test_accy 73.00
Task 1, Epoch 180/180 => Loss 0.002, Train_accy 0.00
 CNN: {'total': 7.36, '00-09': 7.8, 'old': 7.8, 'new': 0.0}
Task 2, Epoch 180/180 => Loss 0.002, Train_accy 0.00
 CNN: {'total': 38.67, '00-09': 46.4, '10-19': 0.0, 'old': 43.77, 'new': 0.0}
Task 3, Epoch 180/180 => Loss 0.003, Train_accy 0.00
 CNN: {'total': 12.99, '00-09': 17.4, '10-19': 0.0, 'old': 14.5, 'new': 0.0}
...
Task 9, Epoch 180/180 => Loss 0.004, Train_accy 0.00
 CNN: {'total': 28.66, '00-09': 55.6, '10-19': 0.0, 'old': 30.89, 'new': 0.0}
CNN top1 curve: [74.0, 7.36, 38.67, 12.99, 1.22, 23.83, 34.52, 16.55, 8.56, 28.66]
CNN top5 curve: [98.6, 52.26, 78.0, 45.82, 29.05, 53.58, 57.26, 48.85, 31.78, 48.66]
```

I also tried it on Lwf, the problem remains.

### Questions About Loss Function

I am wondering whether issues exist in the loss function. And I found that the loss function is defined as: `loss_clf = F.cross_entropy(logits[:,self._known_classes:],targets-self._known_classes)`, along with `loss_ewc`. 

In my experiments, I set `base_session=10`, `increment=1`. So for task1, when calculating the loss, `targets=[10, 10, ..., 10]` and `self._known_classes=10`. Therefore, the target(#2para) of the `cross_entropy` was [0, 0, ..., 0]. **Is that mean the loss function pushes the model to reject the new task, making `logits` of the new task approach 0?**

### Tuning Loss Function

I tried to change the #2para to [1, 1, ..., 1] by setting `targets-self._known_classes+1`, but error arises:
```
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [1,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:108: cunn_ClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
...
Traceback (most recent call last):
  File "/tmp/pycharm_project_241/main.py", line 33, in <module>
    main()
  File "/tmp/pycharm_project_241/main.py", line 13, in main
    train(args)
  File "/tmp/pycharm_project_241/trainer.py", line 18, in train
    _train(args)
  File "/tmp/pycharm_project_241/trainer.py", line 48, in _train
    model.incremental_train(data_manager)
  File "/tmp/pycharm_project_241/models/ewc.py", line 62, in incremental_train
    self._train(self.train_loader, self.test_loader)
  File "/tmp/pycharm_project_241/models/ewc.py", line 84, in _train
    self._update_representation(train_loader, test_loader, optimizer, scheduler)
  File "/tmp/pycharm_project_241/models/ewc.py", line 138, in _update_representation
    loss.backward()
  File "/home/linkdata/data/yaoxinjie/anaconda3/envs/FACT18/lib/python3.7/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/linkdata/data/yaoxinjie/anaconda3/envs/FACT18/lib/python3.7/site-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Unable to find a valid cuDNN algorithm to run convolution
```

And I don't why it happens and how to handle this. Could you please help me to clarify it? Thanks a lot!

**Comment by G-U-N** [comment]
Substitute the  
```python
loss_clf = F.cross_entropy(logits[:,self._known_classes:],targets-self._known_classes)
```
for 
```python
loss_clf = F.cross_entropy(logits,targets)
```
and you might get the right training results. The first one fails when the `increment` is set to 1.

By the way, remember to adjust the hyperparameter `lambda` and use the `gradient clip` to avoid the gradient exploding and achieve better results when you apply the method `ewc` to your own datasets.

**Comment by Steven-cpp** [comment]
Thanks a lot, it works! The training result on new task1 has come near 95%.👏

But will it transform the method into fine-tuning, thus degrading EWC's performance against catastorfic forgetting?

**Comment by G-U-N** [comment]
It probably affects the performance of `EWC`, but that does not mean that it will degrade to `finetune`  since `finetune` does not have `loss_ewc`.
